using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using System.Windows.Shell;

namespace Arksplorer
{
    // temporary class for some reading in of data, not used live but in development
    public class KeyValue
    {
        [JsonPropertyName("ClassName")]
        public string Key { get; set; }
        [JsonPropertyName("FriendlyName")]
        public string Value { get; set; }
    }

    public static class Lookup
    {
        // Used to read in json and convert into direct key/value pairs (for speed)
        public static void CodeGenerator()
        {
            List<KeyValue> l = JsonSerializer.Deserialize<List<KeyValue>>(File.ReadAllText("./temp.json"));

            foreach (KeyValue ab in l)
            {
                Debug.Print($"{{\"{ab.Key}\", \"{ab.Value}\"}},");
            }

        }

        public static Dictionary<string, string> ClassToDinoNames { get; set; } = new()
        {
            { "Achatina_Character_BP_C", "Achatina" },
            { "Allo_Character_BP_C", "Allosaurus" },
            { "Ammonite_Character_C", "Ammonite" },
            { "Angler_Character_BP_C", "Anglerfish" },
            { "Ankylo_Character_BP_C", "Ankylosaurus" },
            { "SpiderS_Character_BP_C", "Araneo" },
            { "Archa_Character_BP_C", "Archaeopteryx" },
            { "Argent_Character_BP_C", "Argentavis" },
            { "Arthro_Character_BP_C", "Arthropluera" },
            { "Baryonyx_Character_BP_C", "Baryonyx" },
            { "Basilosaurus_Character_BP_C", "Basilosaurus" },
            { "Toad_Character_BP_C", "Beelzebufo" },
            { "Sauropod_Character_BP_C", "Brontosaurus" },
            { "Turtle_Character_BP_C", "Carbonemys" },
            { "Carno_Character_BP_C", "Carnotaurus" },
            { "Beaver_Character_BP_C", "Castoroides" },
            { "Chalico_Character_BP_C", "Chalicotherium" },
            { "ChalkGolem_Character_BP_C", "Chalk Golem" },
            { "Cnidaria_Character_BP_C", "Cnidaria" },
            { "Coel_Character_BP_Ocean_C", "Coelacanth (Ocean)" },
            { "Coel_Character_BP_C", "Coelacanth" },
            { "Compy_Character_BP_C", "Compy" },
            { "Daeodon_Character_BP_C", "Daeodon" },
            { "Deathworm_Character_BP_C", "Deathworm" },
            { "Deinonychus_Character_BP_C", "Deinonychus" },
            { "Dilo_Character_BP_C", "Dilophosaur" },
            { "Dimetro_Character_BP_C", "Dimetrodon" },
            { "Dimorph_Character_BP_C", "Dimorphodon" },
            { "Diplocaulus_Character_BP_C", "Diplocaulus" },
            { "Diplodocus_Character_BP_C", "Diplodocus" },
            { "Direbear_Character_BP_C", "Dire Bear" },
            { "Direbear_LL_Character_BP_C", "Dire Bear" },
            { "Direwolf_LL_Character_BP_C", "Dire Wolf" },
            { "Direwolf_Character_BP_C", "Dire Wolf" },
            { "Leech_Character_Diseased_C", "Diseased Leech" },
            { "Dodo_Character_BP_C", "Dodo" },
            { "Doed_Character_BP_C", "Doedicurus" },
            { "DungBeetle_Character_BP_C", "Dung Beetle" },
            { "Dunkle_Character_BP_C", "Dunkleosteus" },
            { "Eel_Character_BP_C", "Electrophorus" },
            { "Equus_Character_BP_C", "Equus" },
            { "Euryp_Character_C", "Eurypterid" },
            { "Wyvern_Character_BP_Fire_C", "Fire Wyvern" },
            { "Galli_Character_BP_C", "Gallimimus" },
            { "Bee_Queen_Character_BP_C", "Giant Queen Bee" },
            { "Gigant_Character_BP_C", "Giganotosaurus" },
            { "Gigant_Character_BP_TekCave_C", "Giganotosaurus" },
            { "Bigfoot_Character_BP_C", "Gigantopithecus" },
            { "Hesperornis_Character_BP_C", "Hesperornis" },
            { "Hyaenodon_Character_BP_C", "Hyaenodon" },
            { "IceGolem_Character_BP_C", "Ice Golem" },
            { "Ragnarok_Wyvern_Override_Ice_C", "Ice Wyvern" },
            { "Ichthyornis_Character_BP_C", "Ichthyornis" },
            { "Dolphin_Character_BP_C", "Ichthyosaurus" },
            { "Iguanodon_Character_BP_C", "Iguanodon" },
            { "Jerboa_Character_BP_C", "Jerboa" },
            { "Kairuku_Character_BP_C", "Kairuku" },
            { "Kaprosuchus_Character_BP_C", "Kaprosuchus" },
            { "Kentro_Character_BP_C", "Kentrosaurus" },
            { "Lamprey_Character_C", "Lamprey" },
            { "Leech_Character_C", "Leech" },
            { "Leedsichthys_Character_BP_C", "Leedsichthys" },
            { "Moth_Character_BP_C", "Lymantria" },
            { "Lystro_Character_BP_C", "Lystrosaurus" },
            { "Mammoth_Character_BP_C", "Mammoth" },
            { "Manta_Character_BP_C", "Manta" },
            { "Mantis_Character_BP_C", "Mantis" },
            { "Stag_Character_BP_C", "Megaloceros" },
            { "Megalodon_Character_BP_C", "Megalodon" },
            { "Dragonfly_Character_BP_C", "Meganeura" },
            { "Megatherium_Character_BP_C", "Megatherium" },
            { "Megalosaurus_Character_BP_C", "Megalosaurus" },
            { "Monkey_Character_BP_C", "Mesopithecus" },
            { "Microraptor_Character_BP_C", "Microraptor" },
            { "camelsaurus_Character_BP_C", "Morellatops" },
            { "Mosa_Character_BP_C", "Mosasaurus" },
            { "Moschops_Character_BP_C", "Moschops" },
            { "Bat_Character_BP_C", "Onyc" },
            { "Otter_Character_BP_C", "Otter" },
            { "Oviraptor_Character_BP_C", "Oviraptor" },
            { "Sheep_Character_BP_C", "Ovis" },
            { "Jugbug_Oil_Character_BP_C", "Oil Jugbug" },
            { "Pachy_Character_BP_C", "Pachy" },
            { "Pachyrhino_Character_BP_C", "Pachyrhinosaurus" },
            { "Paracer_Character_BP_C", "Paraceratherium" },
            { "Para_Character_BP_C", "Parasaur" },
            { "Pegomastax_Character_BP_C", "Pegomastax" },
            { "Pela_Character_BP_C", "Pelagornis" },
            { "Phiomia_Character_BP_C", "Phiomia" },
            { "Phoenix_Character_BP_C", "Phoenix" },
            { "Piranha_Character_BP_C", "Piranha" },
            { "Plesiosaur_Character_BP_C", "Plesiosaur" },
            { "Direbear_Character_Polar_C", "Polar Bear" },
            { "Polar_Bear_C", "Polar Bear" },
            { "Procoptodon_Character_BP_C", "Procoptodon" },
            { "Ptero_Character_BP_C", "Pteranodon" },
            { "Scorpion_Character_BP_C", "Pulmonoscorpius" },
            { "Purlovia_Character_BP_C", "Purlovia" },
            { "Purlovia_Character_BP_Polar_C", "Purlovia (Polar)" },
            { "Quetz_Character_BP_C", "Quetzal" },
            { "Raptor_Character_BP_C", "Raptor" },
            { "Rex_Character_BP_C", "Rex" },
            { "Salmon_Character_BP_C", "Sabertooth Salmon" },
            { "Saber_Character_BP_C", "Sabertooth" },
            { "Sarco_Character_BP_C", "Sarco" },
            { "Spino_Character_BP_C", "Spinosaur" },
            { "Stego_Character_BP_C", "Stegosaurus" },
            { "Tapejara_Character_BP_C", "Tapejara" },
            { "TerrorBird_Character_BP_C", "Terror Bird" },
            { "Therizino_Character_BP_C", "Therizinosaur" },
            { "SpineyLizard_Character_BP_C", "Thorny Dragon" },
            { "Thylacoleo_Character_BP_C", "Thylacoleo" },
            { "BoaFrill_Character_BP_C", "Titanoboa" },
            { "Ant_Character_BP_C", "Titanomyrma Drone" },
            { "FlyingAnt_Character_BP_C", "Titanomyrma Soldier" },
            { "Titanosaur_Character_BP_C", "Titanosaur" },
            { "Trike_Character_BP_C", "Triceratops" },
            { "Trilobite_Character_C", "Trilobite" },
            { "Troodon_Character_BP_C", "Troodon" },
            { "Tusoteuthis_Character_BP_C", "Tusoteuthis" },
            { "Equus_Character_BP_Unicorn_C", "Unicorn" },
            { "Spindles_Character_BP_C", "Velonasaur" },
            { "Jugbug_Water_Character_BP_C", "Water Jugbug" },
            { "Rhino_Character_BP_C", "Woolly Rhino" },
            { "Yeti_Character_BP_C", "Yeti" },
            { "Yutyrannus_Character_BP_C", "Yutyrannus" },
            { "BionicPara_Character_BP_C", "Tek Parasaur" },
            { "BionicQuetz_Character_BP_C", "Tek Quetz" },
            { "BionicRaptor_Character_BP_C", "Tek Raptor" },
            { "BionicRex_Character_BP_C", "Tek Rex" },
            { "BionicStego_Character_BP_C", "Tek Stegosaurus" },
            { "Achatina_Character_BP_Aberrant_C", "Aberrant Achatina" },
            { "Angler_Character_BP_Aberrant_C", "Aberrant Anglerfish" },
            { "Ankylo_Character_BP_Aberrant_C", "Aberrant Ankylosaurus" },
            { "SpiderS_Character_BP_Aberrant_C", "Aberrant Araneo" },
            { "Arthro_Character_BP_Aberrant_C", "Aberrant Arthropluera" },
            { "Baryonyx_Character_BP_Aberrant_C", "Aberrant Baryonyx" },
            { "Toad_Character_BP_Aberrant_C", "Aberrant Beelzebufo" },
            { "Turtle_Character_BP_Aberrant_C", "Aberrant Carbonemys" },
            { "Carno_Character_BP_Aberrant_C", "Aberrant Carnotaurus" },
            { "Coel_Character_BP_Aberrant_C", "Aberrant Coelacanth" },
            { "Cnidaria_Character_BP_Aberrant_C", "Aberrant Cnidaria" },
            { "Dimetro_Character_BP_Aberrant_C", "Aberrant Dimetrodon" },
            { "Dimorph_Character_BP_Aberrant_C", "Aberrant Dimorphodon" },
            { "Diplocaulus_Character_BP_Aberrant_C", "Aberrant Diplocaulus" },
            { "Diplodocus_Character_BP_Aberrant_C", "Aberrant Diplodocus" },
            { "Direbear_Character_BP_Aberrant_C", "Aberrant Dire Bear" },
            { "Dodo_Character_BP_Aberrant_C", "Aberrant Dodo" },
            { "Doed_Character_BP_Aberrant_C", "Aberrant Doedicurus" },
            { "Eel_Character_BP_Aberrant_C", "Aberrant Electrophorus" },
            { "Equus_Character_BP_Aberrant_C", "Aberrant Equus" },
            { "Iguanodon_Character_BP_Aberrant_C", "Aberrant Iguanodon" },
            { "Lystro_Character_BP_Aberrant_C", "Aberrant Lystrosaurus" },
            { "Manta_Character_BP_Aberrant_C", "Aberrant Manta" },
            { "Megalania_Character_BP_C", "Megalania" },
            { "Liopleurodon_Character_BP_C", "Liopleurodon" },
            { "Megalania_Character_BP_Aberrant_C", "Aberrant Megalania" },
            { "Megalosaurus_Character_BP_Aberrant_C", "Aberrant Megalosaurus" },
            { "Dragonfly_Character_BP_Aberrant_C", "Aberrant Meganeura" },
            { "Moschops_Character_BP_Aberrant_C", "Aberrant Moschops" },
            { "Otter_Character_BP_Aberrant_C", "Aberrant Otter" },
            { "Sheep_Character_BP_Aberrant_C", "Aberrant Ovis" },
            { "Paracer_Character_BP_Aberrant_C", "Aberrant Paraceratherium" },
            { "Para_Character_BP_Aberrant_C", "Aberrant Parasaur" },
            { "Piranha_Character_BP_Aberrant_C", "Aberrant Piranha" },
            { "Scorpion_Character_BP_Aberrant_C", "Aberrant Pulmonoscorpius" },
            { "Purlovia_Character_BP_Aberrant_C", "Aberrant Purlovia" },
            { "Raptor_Character_BP_Aberrant_C", "Aberrant Raptor" },
            { "Salmon_Character_Aberrant_C", "Aberrant Salmon" },
            { "Sarco_Character_BP_Aberrant_C", "Aberrant Sarco" },
            { "Spino_Character_BP_Aberrant_C", "Aberrant Spino" },
            { "Stego_Character_BP_Aberrant_C", "Aberrant Stegosaurus" },
            { "BoaFrill_Character_BP_Aberrant_C", "Aberrant Titanoboa" },
            { "Trike_Character_BP_Aberrant_C", "Aberrant Triceratops" },
            { "Trilobite_Character_Aberrant_C", "Aberrant Trilobite" },
            { "LanternPug_Character_BP_C", "Bulbdog" },
            { "LanternBird_Character_BP_C", "Featherlight" },
            { "Lightbug_Character_BaseBP_C", "Glowbug" },
            { "LanternLizard_Character_BP_C", "Glowtail" },
            { "Crab_Character_BP_C", "Karkinos" },
            { "CaveWolf_Character_BP_C", "Ravager" },
            { "MoleRat_Character_BP_C", "Roll Rat" },
            { "Pteroteuthis_Char_BP_C", "Seeker" },
            { "Xenomorph_Character_BP_Male_C", "Reaper" },
            { "Xenomorph_Character_BP_Male_Chupa_C", "Reaper King" },
            { "Xenomorph_Character_BP_Male_Minion_C", "Reaper King" },
            { "Xenomorph_Character_BP_Female_C", "Reaper Queen" },
            { "ChupaCabra_Character_BP_C", "Nameless" },
            { "RockDrake_Character_BP_C", "Rock Drake" },
            { "EndDrone_Character_BP_C", "Attack Drone" },
            { "EndDrone_Character_BP_Hard_C", "Attack Drone" },
            { "EndDrone_Character_BP_Med_C", "Attack Drone" },
            { "EndDrone_Character_BP_Easy_C", "Attack Drone" },
            { "Basilisk_Character_BP_C", "Basilisk" },
            { "Arthro_Character_BP_Corrupt_C", "Corrupted Arthropluera" },
            { "Carno_Character_BP_Corrupt_C", "Corrupted Carnotaurus" },
            { "Chalico_Character_BP_Corrupt_C", "Corrupted Chalicotherium" },
            { "CorruptTumor_Character_BP_C", "Corrupt Tumor" },
            { "Dilo_Character_BP_Corrupt_C", "Corrupted Dilophosaur" },
            { "Dimorph_Character_BP_Corrupt_C", "Corrupted Dimorphodon" },
            { "Gigant_Character_BP_Corrupt_C", "Corrupted Giganotosaurus" },
            { "Paracer_Character_BP_Corrupt_C", "Corrupted Paraceratherium" },
            { "Ptero_Character_BP_Corrupt_C", "Corrupted Pteranodon" },
            { "Raptor_Character_BP_Corrupt_C", "Corrupted Raptor" },
            { "Xenomorph_Character_BP_Male_Tamed_Corrupt_C", "Corrupted Reaper King" },
            { "Rex_Character_BP_Corrupt_C", "Corrupted Rex" },
            { "RockDrake_Character_BP_Corrupt_C", "Corrupted Rock Drake" },
            { "Spino_Character_BP_Corrupt_C", "Corrupted Spino" },
            { "Stego_Character_BP_Corrupt_C", "Corrupted Stegosaurus" },
            { "Trike_Character_BP_Corrupt_C", "Corrupted Triceratops" },
            { "Wyvern_Character_BP_Fire_Corrupt_C", "Corrupted Wyvern" },
            { "EndTank_Character_BP_C", "Defense Unit" },
            { "Enforcer_Character_BP_C", "Enforcer" },
            { "Gacha_Character_BP_C", "Gacha" },
            { "Gacha_Claus_Character_BP_C", "Gacha Claus" },
            { "GasBags_Character_BP_C", "Gasbags" },
            { "IceJumper_Character_BP_C", "Managarmr" },
            { "Mek_Character_BP_C", "Mek" },
            { "MegaMek_Character_BP_C", "Mega Mek" },
            { "Scout_Character_BP_C", "Scout" },
            { "Owl_Character_BP_C", "Snow Owl" },
            { "Griffin_Character_BP_C", "Griffin" },
            { "Griffin_Character_Minion_BP_C", "Griffin" },
            { "Iceworm_Character_Minion_BP_smaller_C", "Iceworm" },
            { "LavaGolem_Character_BP_C", "Lava Golem" },
            { "Wyvern_Character_BP_Lightning_C", "Lightning Wyvern" },
            { "Wyvern_Character_BP_Poison_C", "Poison Wyvern" },
            { "MegaBasilisk_Character_BP_C", "Alpha Basilisk" },
            { "MegaCarno_Character_BP_C", "Alpha Carnotaurus" },
            { "MegaDeathworm_Character_BP_C", "Alpha Deathworm" },
            { "MegaWyvern_Character_BP_Fire_C", "Alpha Fire Wyvern" },
            { "MegaCrab_Character_BP_C", "Alpha Karkinos" },
            { "Alpha_Leedsichthys_Character_BP_C", "Alpha Leedsichthys" },
            { "Mosa_Character_BP_Mega_C", "Alpha Mosasaur" },
            { "Mosa_Character_BP_Mega_Cave_C", "Alpha Mosasaur (Cave)" },
            { "MegaMegalodon_Character_BP_C", "Alpha Megalodon" },
            { "MegaRaptor_Character_BP_C", "Alpha Raptor" },
            { "MegaRex_Character_BP_C", "Alpha T-Rex" },
            { "Mega_Tusoteuthis_Character_BP_C", "Alpha Tusoteuthis" },
            { "MegaXenomorph_Character_BP_Male_Surface_C", "Alpha Reaper King (Surface)" },
            { "MegaRex_Character_BP_Corrupt_C", "Alpha Corrupted Rex" },
            { "Enraged Triceratops", "Alpha Corrupted Triceratops" },
            { "DesertKaiju_FirstFlockChar_BP_C", "Desert Titan Flock" },
            { "DesertKaiju_Character_BP_C", "Desert Titan" },
            { "DesertKaiju_Character_BP_Hard_C", "Desert Titan (Alpha)" },
            { "DesertKaiju_Character_BP_Medium_C", "Desert Titan (Beta)" },
            { "DesertKaiju_Character_BP_Easy_C", "Desert Titan (Gamma)" },
            { "ForestKaiju_Character_BP_C", "Forest Titan" },
            { "ForestKaiju_Character_BP_Hard_C", "Forest Titan (Alpha)" },
            { "ForestKaiju_Character_BP_Medium_C", "Forest Titan (Beta)" },
            { "ForestKaiju_Character_BP_Easy_C", "Forest Titan (Gamma)" },
            { "IceKaiju_Character_BP_C", "Ice Titan" },
            { "IceKaiju_Character_BP_Hard_C", "Ice Titan (Alpha)" },
            { "IceKaiju_Character_BP_Medium_C", "Ice Titan (Beta)" },
            { "IceKaiju_Character_BP_Easy_C", "Ice Titan (Gamma)" },
            { "KingKaiju_Character_BP_Alpha_C", "King Titan (Alpha)" },
            { "KingKaiju_Character_BP_Beta_C", "King Titan (Beta)" },
            { "KingKaiju_Character_BP_Gamma_C", "King Titan (Gamma)" },
            { "Dragon_Character_BP_Boss_Hard_C", "Dragon (Alpha)" },
            { "Dragon_Character_BP_Boss_Medium_C", "Dragon (Beta)" },
            { "Dragon_Character_BP_Boss_Easy_C", "Dragon (Gamma)" },
            { "Dragon_Character_BP_Boss_Hard_Ragnarok_C", "Dragon (Alpha)" },
            { "Dragon_Character_BP_Boss_Medium_Ragnarok_C", "Dragon (Beta)" },
            { "Dragon_Character_BP_Boss_Easy_Ragnarok_C", "Dragon (Gamma)" },
            { "EndBossSpiderL_Character_BP_C", "Broodmother" },
            { "EndBossSpiderL_Character_BP_Hard_C", "Broodmother (Alpha)" },
            { "EndBossSpiderL_Character_BP_Medium_C", "Broodmother (Beta)" },
            { "EndBossSpiderL_Character_BP_Easy_C", "Broodmother (Gamma)" },
            { "SpiderL_Character_BP_Hard_C", "Broodmother (Alpha)" },
            { "SpiderL_Character_BP_Medium_C", "Broodmother (Beta)" },
            { "SpiderL_Character_BP_Easy_C", "Broodmother (Gamma)" },
            { "SpiderL_Character_BP_TheCenterHard_C", "Broodmother (Alpha)" },
            { "SpiderL_Character_BP_TheCenterMedium_C", "Broodmother (Beta)" },
            { "SpiderL_Character_BP_TheCenterEasy_C", "Broodmother (Gamma)" },
            { "SpiderL_VAL_Character_BP_C", "Valguero Broodmother" },
            { "SpiderL_Character_BP_C", "Dominus Broodmother" },
            { "Gorilla_Character_BP_Hard_C", "Megapithecus (Alpha)" },
            { "Gorilla_Character_BP_Medium_C", "Megapithecus (Beta)" },
            { "Gorilla_Character_BP_Easy_C", "Megapithecus (Gamma)" },
            { "Gorilla_Character_BP_TheCenter_Hard_C", "Megapithecus (Alpha)" },
            { "Gorilla_Character_BP_TheCenter_Medium_C", "Megapithecus (Beta)" },
            { "Gorilla_Character_BP_TheCenter_Easy_C", "Megapithecus (Gamma)" },
            { "Iceworm_Queen_Character_BP_C", "Iceworm Queen" },
            { "Manticore_Character_BP_C", "Manticore" },
            { "Manticore_Character_BP_Hard_C", "Manticore (Alpha)" },
            { "Manticore_Character_BP_Medium_C", "Manticore (Beta)" },
            { "Manticore_Character_BP_Easy_C", "Manticore (Gamma)" },
            { "Manticore_Character_BP_Hard_Ragnarok_C", "Manticore (Alpha)" },
            { "Manticore_Character_BP_Medium_Ragnarok_C", "Manticore (Beta)" },
            { "Manticore_Character_BP_Easy_Ragnarok_C", "Manticore (Gamma)" },
            { "Bone_MegaWyvern_Character_BP_Fire_C", "Bone Fire Wyvern" },
            { "DodoWyvern_Character_BP_C", "Dodo Wyvern" },
            { "DodoRex_Character_BP_C", "Dodo Rex" },
            { "Bone_Sauropod_Character_BP_C", "Skeletal Bronto" },
            { "Bone_MegaCarno_Character_BP_C", "Skeletal Carnotaurus" },
            { "Bone_Gigant_Character_BP_C", "Skeletal Gigantosaurus" },
            { "Bone_Jerboa_Character_BP_C", "Skeletal Jerboa" },
            { "Bone_Quetz_Character_BP_C", "Skeletal Quetzal" },
            { "Bone_MegaRaptor_Character_BP_C", "Skeletal Raptor" },
            { "Bone_MegaRex_Character_BP_C", "Skeletal Rex" },
            { "Bone_Stego_Character_BP_C", "Skeletal Stego" },
            { "Bone_Trike_Character_BP_C", "Skeletal Trike" },
            { "Wyvern_Character_BP_ZombieFire", "Zombie Fire Wyvern" },
            { "Wyvern_Character_BP_ZombieLightning", "Zombie Lightning Wyvern" },
            { "Wyvern_Character_BP_ZombiePoison", "Zombie Poison Wyvern" },
            { "Wyvern_Character_BP_ZombieFire_C", "Zombie Fire Wyvern" },
            { "Wyvern_Character_BP_ZombieLightning_C", "Zombie Lightning Wyvern" },
            { "Wyvern_Character_BP_ZombiePoison_C", "Zombie Poison Wyvern" },
            { "ZombieWyvern_Character_BP_Fire_C", "Zombie Fire Wyvern" },
            { "ZombieWyvern_Character_BP_Poison_C", "Zombie Poison Wyvern" },
            { "ZombieWyvern_Character_BP_Lightning_C", "Zombie Lightning Wyvern" },
            { "ZombieDodo_Character_BP_C", "Zomdodo" },
            { "Turkey_Character_BP_C", "Turkey" },
            { "MotorRaft_BP_C", "Motorboat" },
            { "Raft_BP_C", "Raft" },
            { "RockGolem_Character_BP_C", "Rock Elemental" },
            { "RubbleGolem_Character_BP_C", "Rubble Golem" },
            { "Vulture_Character_BP_C", "Vulture" },
            { "Bigfoot_Character_BP_Aberrant_C", "Aberrant Gigantopithecus" },
            { "ChupaCabra_Character_BP_Surface_C", "Nameless (Surface)" },
            { "DungBeetle_Character_BP_Aberrant_C", "Aberrant Dung Beetle" },
            { "LanternGoat_Character_BP_C", "Shinehorn" },
            { "Pteroteuthis_Char_BP_Surface_C", "Seeker (Surface)" },
            { "Xenomorph_Character_BP_Male_Surface_C", "Reaper King (Surface)" },
            { "Xenomorph_Character_BP_Male_Tamed_C", "Reaper King" },
            { "BionicTrike_Character_BP_C", "Tek Trike" },
            { "Bog_Para_Character_BP_C", "X-Parasaur" },
            { "Bog_Paracer_Character_BP_C", "X-Paracer" },
            { "Bog_Raptor_Character_BP_C", "X-Raptor" },
            { "Bog_Spino_Character_BP_C", "X-Spino" },
            { "BogSpider_Character_BP_C", "Bloodstalker" },
            { "Cherufe_Character_BP_C", "Magmasaur" },
            { "EndDrone_Lunar_Character_BP_C", "X-Drone" },
            { "EndTank_Lunar_Character_BP_C", "X-Defense Unit" },
            { "GiantTurtle_Character_BP_C", "Megachelon" },
            { "InsectSwarmChar_BP_C", "Insect Swarm" },
            { "Lunar_Salmon_Character_BP_C", "X-Salmon" },
            { "Ocean_Basilosaurus_Character_BP_C", "X-Basilosaurus" },
            { "Ocean_Dolphin_Character_BP_C", "X-Ichthyosaurus" },
            { "Ocean_Dunkle_Character_BP_C", "X-Dunkleosteus" },
            { "Ocean_Megalodon_Character_BP_C", "X-Megalodon" },
            { "Ocean_Mosa_Character_BP_C", "X-Mosasaur" },
            { "Rare_Lunar_Salmon_Character_BP_C", "X-Salmon (Rare)" },
            { "Shapeshifter_Small_Character_BP_C", "Ferox (Small)" },
            { "Shapeshifter_Large_Character_BP_C", "Ferox (Large)" },
            { "SpaceWhale_Character_BP_C", "Astrocetus" },
            { "MicrobeSwarmChar_BP_C", "Parakeet Fish School" },
            { "Volcano_Golem_Character_BP_C", "X-Rock Elemental" },
            { "Xenomorph_Character_BP_Male_Lunar_C", "X-Reaper King" },
            { "Bog_Tapejara_Character_BP_C", "X-Tapejara" },
            { "Snow_Argent_Character_BP_C", "X-Argentavis" },
            { "Snow_Rhino_Character_BP_C", "X-Rhino" },
            { "Snow_Saber_Character_BP_C", "X-Sabertooth" },
            { "Snow_Yutyrannus_Character_BP_C", "X-Yutyrannus" },
            { "Volcano_Allo_Character_BP_C", "X-Allosaurus" },
            { "Volcano_Ankylo_Character_BP_C", "X-Ankylosaurus" },
            { "Volcano_Rex_Character_BP_C", "X-Rex" },
            { "Volcano_Trike_Character_BP_C", "X-Triceratops" },
            { "Snow_Otter_Character_BP_C", "X-Otter" }
        };
    }
}
